# version: '3.8' depreciated

services:
  web:
    build: .
    # Removes any stale server PIDs before booting up the server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    volumes:
      # 1. Bind mount: Maps your local code to the container for instant live-reloading
      - .:/rails_app:cached
      # 2. Named volume: Caches Ruby gems in the container so you don't lose them on rebuilds
      - gem_cache:/usr/local/bundle
      # 3. Named volume: Mounts the storage/ folder separately to safely persist your SQLite database file
      - rails_storage:/rails_app/storage
      # 4. Named volume: Mounts the log/ and tmp/ folders separately to safely persist your development/production logs
      #- rails_log:/rails_app/log
      #- rails_log:/rails_app/tmp
      # 5. Named volume: Mounts the public/ folder separately to safely persist your compiled assets and packs
      - rails_public_assets:/rails_app/public/

      # 6. Anonymous volumes: Keeps noisy logs and tmp files contained inside Docker
      - /rails_app/tmp
      - /rails_app/log
    stdin_open: true
    tty: true


volumes:
  gem_cache:           # Caches Ruby gems in the container so you don't lose them on rebuilds
  rails_storage:       # Persists your SQLite database (Rails 8 defaults SQLite here)
  # rails_log:           # Persists development/production logs
  rails_public_assets: # Persists your compiled assets and packs
